# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 737d03583da6588b6c146e97850e74a11c2c6898a0fecbc96edaf5f772b90a1a9dad1ca4866cdccf05743a110549eedf3306c8581ab25737592a156f5edaff76

test:
  secret_key_base: ae728756d814e48982d12e616407d91250438eb19eb40517d6615b0d56a8d10586dcbc26d7414e654475538e1d6fe5e67ab3a66da45a2a9befe346f54e2b9cbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
